apiVersion: apps/v1
kind: Deployment
metadata:
  name: health
spec:
  replicas: 3 
  selector:
    matchLabels:
      app: health
  template:
    metadata:
      labels:
        app: health
    spec:
      containers:
        - name: health-server
          image: yadon3141/health
          ports:
            - containerPort: 8080
            