apiVersion: v1
kind: Service
metadata:
  name: health-service
spec:
  selector:
    app: health
  ports:
    - name: http
      protocol: TCP
      port: 8080
      targetPort: 8080
  type: LoadBalancer
  