apiVersion: minio.min.io/v2
kind: Tenant
metadata:
  name: minio-tenant
  namespace: minio
spec:
  image: quay.io/minio/minio:RELEASE.2025-09-07T16-13-09Z
  pools:
    - name: pool-0
      servers: 4
      volumesPerServer: 1
      env:
        - name: MINIO_ROOT_USER
          valueFrom:
            secretKeyRef:
              name: minio-creds-secret
              key: accesskey
        - name: MINIO_ROOT_PASSWORD
          valueFrom:
            secretKeyRef:
              name: minio-creds-secret
              key: secretkey
      volumeClaimTemplate:
        metadata:
          name: data
        spec:
          accessModes: ["ReadWriteOnce"]
          resources:
            requests:
              storage: 50Gi
          storageClassName: longhorn
  mountPath: /export
  requestAutoCert: false
  exposeServices:
    console: false
    minio: false
