version: '3'
services:
  prometheus:
    image: prom/prometheus:v2.41.0
    container_name: prometheus
    volumes:
      - ./:/etc/prometheus/
      - ./prometheus-data:/prometheus
    ports:
      - 9090:9090
    network_mode: dockernet