apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: manifest
  namespace: argocd
spec:
  project: default
  destination:
    namespace: manifest
    server: https://kubernetes.default.svc
  source:
    repoURL: https://github.com/yadon-infra/manifest
    targetRevision: main
  syncPolicy:
    automated:
      prune: true