apiVersion: batch/v1
kind: CronJob
metadata:
  name: rsa-key-generator
spec:
  schedule: "0 1 * * *"  # 毎日午前1時に実行
  jobTemplate:
    spec:
      template:
        spec:
          containers:
          - name: rsa-key-generator
            image: your-docker-repo/rsa-key-generator:latest
            volumeMounts:
            - name: keys-volume
              mountPath: /keys
          restartPolicy: OnFailure
          volumes:
          - name: keys-volume
            persistentVolumeClaim:
              claimName: keys-pvc
